// GET CUSTOMERS
export const FETCH_CUSTOMERS_REQUEST = 'FETCH_CUSTOMERS_REQUEST'
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS'
export const FETCH_CUSTOMERS_ERROR = 'FETCH_CUSTOMERS_ERROR'

export const CREATE_CUSTOMER_REQUEST = 'CREATE_CUSTOMER_REQUEST'

export const DELETE_CUSTOMER_REQUEST = 'DELETE_CUSTOMER_REQUEST'


// GET CUSTOMER
// export const GET_SINGLE_CUSTOMER_REQUEST = 'GET_SINGLE_CUSTOMER_REQUEST'
// export const GET_SINGLE_CUSTOMER_SUCCESS = 'GET_SINGLE_CUSTOMER_SUCCESS'
// export const GET_SINGLE_CUSTOMER_ERROR = 'GET_SINGLE_CUSTOMER_ERROR'


// export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST'




