// GET PRODUCTS
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'


// GET CUSTOMER
// export const GET_SINGLE_CUSTOMER_REQUEST = 'GET_SINGLE_CUSTOMER_REQUEST'
// export const GET_SINGLE_CUSTOMER_SUCCESS = 'GET_SINGLE_CUSTOMER_SUCCESS'
// export const GET_SINGLE_CUSTOMER_ERROR = 'GET_SINGLE_CUSTOMER_ERROR'


// export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST'




